version: '2'

services:
  web:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ".:/src"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    command: nodemon -L index.js